my_duckdb_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: test-postgres
      user: "postgres"
      password: "dbtproject2020*"
      port: 5432  
      dbname: my_project_db
      schema: "public"
