my_duckdb_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "127.0.0.1"  
      user: "postgres"
      password: "Blend2022*"
      port: 5432  
      dbname: my_project_db
      schema: "analytics"
