my_bigquery_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: converteo-ae-recrut-yayoub
      dataset: ecommerce
      threads: 4
      location: EU
      keyfile: /tmp/key.json