version: 2

sources:
  - name: e_commerce_1
    database: converteo-ae-recrut   # READ project
    dataset: e_commerce_1          
    tables:
      - name: orders
      - name: customers 
      - name: order_items
      - name: products 
      - name: product_category_name_translation