name: dbt CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dbt-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Docker network
        run: docker network create dbt-network

      - name: Start PostgreSQL
        run: |
          docker run --name test-postgres \
            --network dbt-network \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=Blend2022* \
            -e POSTGRES_DB=my_project_db \
            -d postgres:12
          sleep 10

      - name: dbt deps
        run: |
          docker run --rm \
            --network dbt-network \
            -v ${{ github.workspace }}:/usr/app \
            -w /usr/app \
            -e DBT_PROFILES_DIR=/usr/app \
            ghcr.io/dbt-labs/dbt-postgres:1.9.0 \
            dbt deps

      - name: dbt build
        run: |
          docker run --rm \
            --network dbt-network \
            -v ${{ github.workspace }}:/usr/app \
            -w /usr/app \
            -e DBT_PROFILES_DIR=/usr/app \
            ghcr.io/dbt-labs/dbt-postgres:1.9.0 \
            dbt build --target dev
